server:
  port: 8080
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  
  
spring:
  application:
    name: Api-gateway
    
  cloud:
    gateway:
      routes:
      - id: Auth-Service
        uri: lb://Auth-Service
        predicates:
        - Path=/api/auth/**  
      - id: BookingOrder-Service 
        uri: lb://BookingOrder-Service
        predicates:
        - Path=/orders/**
      - id: Train-Service
        uri: lb://Train-Service
        predicates:
        - Path=/trains/**

#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#server:
#  port: 8082
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka